// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: credit_limits.sql

package pgmodel

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listCreditLimitsByApp = `-- name: ListCreditLimitsByApp :many
SELECT id, app_id, type, target_id, max_credits, created_at, updated_at FROM credit_limits WHERE app_id = $1 ORDER BY created_at ASC
`

func (q *Queries) ListCreditLimitsByApp(ctx context.Context, appID string) ([]CreditLimit, error) {
	rows, err := q.db.Query(ctx, listCreditLimitsByApp, appID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CreditLimit
	for rows.Next() {
		var i CreditLimit
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.Type,
			&i.TargetID,
			&i.MaxCredits,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCreditLimit = `-- name: UpsertCreditLimit :one
INSERT INTO credit_limits (
    app_id,
    type,
    target_id,
    max_credits,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6
)
ON CONFLICT (app_id, type, target_id) DO UPDATE SET
    max_credits = EXCLUDED.max_credits,
    updated_at = EXCLUDED.updated_at
RETURNING id, app_id, type, target_id, max_credits, created_at, updated_at
`

type UpsertCreditLimitParams struct {
	AppID      string
	Type       string
	TargetID   pgtype.Text
	MaxCredits int32
	CreatedAt  pgtype.Timestamp
	UpdatedAt  pgtype.Timestamp
}

func (q *Queries) UpsertCreditLimit(ctx context.Context, arg UpsertCreditLimitParams) (CreditLimit, error) {
	row := q.db.QueryRow(ctx, upsertCreditLimit,
		arg.AppID,
		arg.Type,
		arg.TargetID,
		arg.MaxCredits,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i CreditLimit
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.Type,
		&i.TargetID,
		&i.MaxCredits,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCreditLimit = `-- name: DeleteCreditLimit :execrows
DELETE FROM credit_limits WHERE app_id = $1 AND type = $2 AND target_id IS NOT DISTINCT FROM $3
`

type DeleteCreditLimitParams struct {
	AppID    string
	Type     string
	TargetID pgtype.Text
}

func (q *Queries) DeleteCreditLimit(ctx context.Context, arg DeleteCreditLimitParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCreditLimit, arg.AppID, arg.Type, arg.TargetID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
